#!/bin/bash
echo "🔄 pb.yaml 수동 통합 가이드"
echo "=================================="
echo ""
echo "1. 백업 생성 (완료됨)"
echo "   ✅ /Users/bjs/Desktop/project/db/pb.yaml.backup"
echo ""
echo "2. 수동 통합 단계:"
echo "   📝 /Users/bjs/Desktop/project/db/pb.yaml 파일을 편집기로 열기"
echo "   📝 pb_file_management_queries.yaml 파일도 함께 열기"
echo ""
echo "3. storedStatements 섹션에 추가할 쿼리들:"
echo "   - 라인 2 이후에 새로운 쿼리 ID들 추가"
echo "   - I_File, S_File_All, S_File_ById 등..."
echo ""
echo "4. initStatements 섹션에 추가할 테이블들:"
echo "   - 라인 327 이후에 새로운 테이블 스키마 추가"
echo "   - tb_files, tb_parking_zone_files 테이블"
echo ""
echo "5. ws4sqlite 재시작"
echo "   - 새로운 스키마 적용을 위해 서버 재시작 필요"
echo ""
echo "📂 참고 파일들:"
echo "   - 원본: /Users/bjs/Desktop/project/db/pb.yaml"
echo "   - 추가할 내용: pb_file_management_queries.yaml"
echo "   - 백업: /Users/bjs/Desktop/project/db/pb.yaml.backup"
echo ""
echo "⚠️  주의: storedStatements와 initStatements 섹션의 들여쓰기를 정확히 맞춰주세요!"
